- hosts: all
  tasks:
  - name: setting up docker yum conf
    yum_repository:
            name: docker
            description: yum conf for docker
            state: present
            baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
            gpgcheck: no

  - command: "yum install docker-ce  --nobest  -y"

  - name: starting docker service
    service:
            name: docker
            state: started
            enabled: yes
  - name: setting python sdk
    command: pip3 install docker
 
  - name: downloading httpd image from dockerhub
    docker_image:
            name: httpd
            source: pull
  - file:
          state: directory
          path: "/var/www/html"

  - copy:
          dest: "/var/www/html/web.html"
          content: "This is my webpage in docker configured by ansible"
  - docker_container:
          name: "mywebserver"
          image: "httpd"
          state: started
          exposed_ports: "80"
          ports: "8080:80"
          volumes: /var/www/html:/usr/local/apache2/htdocs/

